
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 10 16:28:04 CET 2016
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int ECRIR = 24;
  public static final int IDF = 29;
  public static final int ACCOLADEFERMER = 11;
  public static final int OU = 19;
  public static final int CLASS = 21;
  public static final int PLUS = 2;
  public static final int SUP = 14;
  public static final int STATUT = 31;
  public static final int ALORS = 9;
  public static final int VIRGULE = 27;
  public static final int NON = 20;
  public static final int MOINS = 3;
  public static final int INF = 15;
  public static final int PARFER = 7;
  public static final int SINON = 12;
  public static final int TYPE = 32;
  public static final int EGALE = 23;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int EGALEGAL = 16;
  public static final int ACCOLADEOUVERT = 10;
  public static final int DIV = 5;
  public static final int CONSTANTEBOOL = 26;
  public static final int ET = 18;
  public static final int SI = 8;
  public static final int error = 1;
  public static final int PAROUV = 6;
  public static final int CONSTANTECHAINE = 30;
  public static final int POINT_VIRGULE = 28;
  public static final int DIFF = 17;
  public static final int CONSTANTEINT = 25;
  public static final int FIN = 22;
  public static final int FINSI = 13;
}

